version: '3'


volumes:
  database-data:
  cache-data:

networks:
  platform:

services:
  server:
    extends:
      file: server/compose.yaml
      service: nginx

  database:
    extends:
      file: database/compose.yaml
      service: mysql

  cache:
    extends:
      file: cache/compose.yaml
      service: redis

  messaging:
    extends:
      file: messaging/compose.yaml
      service: rabbitmq

  adminer:
    extends:
      file: manager/compose.yaml
      service: adminer