version: '3'


services:
  mysql:
    container_name: mysql
    build: 
      context: mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - platform

  postgres:
    container_name: postgres
    build: 
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - platform